languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://eduardo.reis.com.pt/"
title = "Eduardo Reis - CV"
#googleAnalytics = ""

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#4287f5"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#4287f5"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#4287f5"
pages = 1
# Set this param to 'true' to swap the bar positions
swapColumns = false
footerNote = "2020 © by Inês Almeida   |   ines-almeida.com"
